[package]
name = "CrystalBank"
version = "1.0.0"
description = "A Motoko-based decentralized banking platform for The Chronicles of Auld Ewe TTRPG."
license = "MIT"
authors = [Mutenguna FM Nalubamba <fbmukakanga@gmail.com>"]

[dependencies]
base = { version = "0.1.1", source = "mo:base" }         # Provides standard collection types and utilities.
mo-crypto = { version = "0.1.0", source = "mo:crypto" }  # Cryptographic utilities for Motoko.
mo-utils = { version = "0.1.2", source = "mo:utils" }    # General utility functions for Motoko.
mo-validation = { version = "0.1.0", source = "mo:validation" }  # Input validation utilities.

[canisters]
MacroManager = {
  main = "MacroManager.mo"
  candid = "MacroManager.did"
  wasm = "MacroManager.wasm"
  type = "custom"
  dependencies = ["base", "mo-crypto", "mo-utils", "mo-validation"]
  # entry_points = ["transferRealFuddy", "convertToRealFuddy", "getEconomicHealthIndicators", "adjustAccountBehaviorScore"]
}

[build]
target = "wasm32-unknown-unknown" # Target for compiling the project.
